# Netlify Configuration for Gestion Avicola
# Documentation: https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command - ejecuta Vite para producci칩n
  command = "npm run build"

  # Directorio de publicaci칩n - donde Vite genera los archivos est치ticos
  publish = "dist"

  # Node version
  environment = { NODE_VERSION = "18" }

# Redirects for SPA (Single Page Application)
# Todas las rutas redirigen a index.html para que React Router funcione
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para archivos est치ticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
